version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8.1.4-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: run npm install
          command: cd src && npm install

      - run:
          name: run test cases
          command: cd src && npm run test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
